{**
 *  Light Go Edit project
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey <zaher at parmaja dot com>
 *}
  sGoKeywords =
    'break,'+
    'default,'+
    'func,'+
    'interface,'+
    'select,'+
    'case,'+
    'defer,'+
    'go,'+
    'map,'+
    'struct,'+
    'chan,'+
    'else,'+
    'goto,'+
    'package,'+
    'switch,'+
    'const,'+
    'fallthrough,'+
    'if,'+
    'range,'+
    'type,'+
    'continue,'+
    'for,'+
    'import,'+
    'return,'+
    'var';

  sGOFunctions =
    'println,'+
    'write';

