{**
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey <zaher at parmaja dot com>
 *}

{
  ref: https://www.lua.org/manual/5.1/manual.html
       https://www.lua.org/manual/5.3/manual.html
}

  sLuaKeywords =
    'and,'+
    'break,'+
    'do,'+
    'else,'+
    'elseif,'+
    'end,'+
    'false,'+
    'for,'+
    'function,'+
    'if,'+
    'in,'+
    'local,'+
    'nil,'+
    'not,'+
    'or,'+
    'repeat,'+
    'return,'+
    'terra,'+ //special
    'then,'+
    'true,'+
    'until,'+
    'while';

  sLuaFunctions =
    'integer,'+
    'string,'+
    'boolean,'+
    'char,'+
    //namespaces
    'io,'+
    'self,'+
    'require,'+
    'module,'+
    //functions
    'print,'+
    'tonumber,'+
    'input,'+
    'output,'+
    'type,'+
    'read,'+
    'write';


