[Hooked Modules]
mnWebServer.exe=T
[Non-Hooked Modules]
oleaut32.dll=T
msvcrt.dll=T
ole32.dll=T
tsappcmp.dll=T
LPK.DLL=T
USP10.dll=T
MSCTF.dll=T
uxtheme.dll=T
[Search Dirs]
C:\Program Files\Borland\Delphi7\\Bin\=T
C:\Program Files\Borland\Delphi7\\Imports\=T
C:\Program Files\Borland\Delphi7\\Lib\=T
C:\Program Files\Borland\Delphi7\\Rave5\Lib\=T
C:\Program Files\Borland\Delphi7\\source\clx\=T
C:\Program Files\Borland\Delphi7\\Source\Indy\=T
C:\Program Files\Borland\Delphi7\\source\Internet\=T
C:\Program Files\Borland\Delphi7\\Source\IntraWeb\=T
C:\Program Files\Borland\Delphi7\\Source\Rtl\=T
C:\Program Files\Borland\Delphi7\\source\rtl\common\=T
C:\Program Files\Borland\Delphi7\\source\rtl\Corba45\=T
C:\Program Files\Borland\Delphi7\\source\rtl\Sys\=T
C:\Program Files\Borland\Delphi7\\source\rtl\Win\=T
C:\Program Files\Borland\Delphi7\\Source\Samples\=T
C:\Program Files\Borland\Delphi7\\Source\Soap\=T
C:\Program Files\Borland\Delphi7\\Source\ToolsAPI\=T
C:\Program Files\Borland\Delphi7\\source\vcl\=T
C:\Program Files\Borland\Delphi7\\Source\WebMidas\=T
C:\Program Files\Borland\Delphi7\\source\websnap\=T
C:\Program Files\Borland\Delphi7\\Source\Xml\=T
D:\Work\delphi\etc\ComPort\source\=T
D:\Work\delphi\etc\ExGraphics\=T
D:\Work\delphi\etc\ExpressLib\ExpressCommon\Delphi 6\Sources\=T
D:\Work\delphi\etc\ExpressLib\ExpressEditors Library\Delphi 6\Sources\=T
D:\Work\delphi\etc\ExpressLib\ExpressInplaceEditors\Delphi 6\Sources\=T
D:\Work\delphi\etc\ExpressLib\ExpressQuantumGrid\Delphi 6\Sources\=T
D:\Work\delphi\etc\ImageEN\=T
D:\work\delphi\etc\Indy\Source\=T
D:\Work\delphi\etc\PARSER\=T
D:\Work\delphi\etc\regexpr\=T
d:\work\delphi\etc\RemObjects\Source\=T
D:\Work\delphi\etc\SynEdit\Source\=T
D:\Work\delphi\etc\tplockbox\source\=T
D:\Work\delphi\etc\tpshellshock\source\=T
d:\work\delphi\jobs\tacbord_sql\source\common\=T
d:\work\delphi\jobs\tacbord_sql\source\core\=T
d:\work\delphi\jobs\tacbord_sql\source\lib\=T
d:\work\delphi\jobs\tacbord_sql\source\prot\=T
D:\Work\delphi\lib\Annexes\=T
d:\work\delphi\lib\DluxReports\=T
D:\Work\delphi\lib\Excel\=T
D:\Work\delphi\lib\FBScriptor\=T
D:\Work\delphi\lib\FBViewer\=T
D:\Work\delphi\lib\FBX\core\=T
D:\Work\delphi\lib\FBX\source\=T
D:\Work\delphi\lib\Formals\=T
d:\work\delphi\lib\freemisc\=T
D:\Work\delphi\lib\HashLib\=T
D:\Work\delphi\lib\MiniSocket\source\=T
D:\Work\delphi\lib\MiscCtrls\=T
D:\Work\delphi\lib\MiscLib\=T
D:\Work\delphi\lib\Nova\=T
D:\Work\delphi\lib\numwords\=T
D:\Work\delphi\lib\RosterBoxes\=T
D:\Work\delphi\lib\tb2k\=T
D:\Work\delphi\lib\tb2k\Source\=T
D:\Work\delphi\lib\tb97\=T
D:\Work\delphi\lib\tbx\=T
D:\Work\delphi\lib\terminals\=T
D:\work\delphi\lib\Utils\=T
D:\Work\delphi\lib\VclZip\=T
D:\Work\delphi\lib\Wages\source\=T
d:\work\system\=T
D:\Work\Trials\tpsrmgr\source\=T
