{**
 *
 *  This file is part of the "Mini Library"
 *
 * @url       http://www.sourceforge.net/projects/minilib
 * @license   modifiedLGPL (modified of http://www.gnu.org/licenses/lgpl.html)
 *            See the file COPYING.MLGPL, included in this distribution,
 * @author    Zaher Dirkey <zaher at parmaja dot com>
 *}

  sCppKeywords =
    'abstract,'+
    'alias,'+
    'align,'+
    'asm,'+
    'assert,'+
    'auto,'+
    'body,'+
    'bool,'+
    'break,'+
    'byte,'+
    'case,'+
    'cast,'+
    'catch,'+
    'cdouble,'+
    'cent,'+
    'cfloat,'+
    'char,'+
    'class,'+
    'const,'+
    'continue,'+
    'creal,'+
    'dchar,'+
    'debug,'+
    'default,'+
    'delegate,'+
    'delete,'+
    'deprecated,'+
    'do,'+
    'double,'+
    'else,'+
    'enum,'+
    'export,'+
    'extern,'+
    'false,'+
    'final,'+
    'finally,'+
    'float,'+
    'for,'+
    'foreach,'+
    'function,'+
    'goto,'+
    'idouble,'+
    'if,'+
    'ifloat,'+
    'import,'+
    'in,'+
    'inout,'+
    'int,'+
    'interface,'+
    'invariant,'+
    'ireal,'+
    'is,'+
    'long,'+
    'mixin,'+
    'module,'+
    'new,'+
    'null,'+
    'out,'+
    'override,'+
    'package,'+
    'pragma,'+
    'private,'+
    'protected,'+
    'public,'+
    'real,'+
    'return,'+
    'scope,'+
    'short,'+
    'static,'+
    'struct,'+
    'super,'+
    'switch,'+
    'synchronized,'+
    'template,'+
    'this,'+
    'throw,'+
    'true,'+
    'try,'+
    'typedef,'+
    'typeid,'+
    'typeof,'+
    'ubyte,'+
    'ucent,'+
    'uint,'+
    'ulong,'+
    'union,'+
    'unittest,'+
    'ushort,'+
    'version,'+
    'void,'+
    'volatile,'+
    'wchar,'+
    'while,'+
    'with';

  sCppFunctions =
    'read,'+
    'readln,'+
    'writeln,'+
    'write';


